<?php

namespace Database\Seeders;

use App\Models\Reports\QuotaAllocation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuotaAllocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Beitbridge', 'allocation' => 10],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Beitbridge', 'allocation' => 13],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Beitbridge', 'allocation' => 22],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Beitbridge', 'allocation' => 1],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Beitbridge', 'allocation' => 2],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Beitbridge', 'allocation' => 9],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Beitbridge', 'allocation' => 8],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Beitbridge', 'allocation' => 10],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Beitbridge', 'allocation' => 9],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Beitbridge', 'allocation' => 10],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Beitbridge', 'allocation' => 10],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Beitbridge', 'allocation' => 7],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Beitbridge', 'allocation' => 6],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Beitbridge', 'allocation' => 8],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Beitbridge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Beitbridge', 'allocation' => 7],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Beitbridge', 'allocation' => 8],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Binga', 'allocation' => 14],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Binga', 'allocation' => 12],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Binga', 'allocation' => 10],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Binga', 'allocation' => 8],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Binga', 'allocation' => 10],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Binga', 'allocation' => 1],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Binga', 'allocation' => 1],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Binga', 'allocation' => 3],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Binga', 'allocation' => 1],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Binga', 'allocation' => 1],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Binga', 'allocation' => 5],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Binga', 'allocation' => 6],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Binga', 'allocation' => 6],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Binga', 'allocation' => 5],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Binga', 'allocation' => 5],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Binga', 'allocation' => 19],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Binga', 'allocation' => 20],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Binga', 'allocation' => 20],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Binga', 'allocation' => 17],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Binga', 'allocation' => 17],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Binga', 'allocation' => 31],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Binga', 'allocation' => 24],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Binga', 'allocation' => 28],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Binga', 'allocation' => 26],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Binga', 'allocation' => 26],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Binga', 'allocation' => 27],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Binga', 'allocation' => 22],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Binga', 'allocation' => 12],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Binga', 'allocation' => 9],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Binga', 'allocation' => 17],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Bulilima', 'allocation' => 12],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Bulilima', 'allocation' => 12],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Bulilima', 'allocation' => 11],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Bulilima', 'allocation' => 13],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Bulilima', 'allocation' => 10],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Bulilima', 'allocation' => 0],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Bulilima', 'allocation' => 3],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Bulilima', 'allocation' => 3],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Bulilima', 'allocation' => 3],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Bulilima', 'allocation' => 3],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Bulilima', 'allocation' => 3],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Bulilima', 'allocation' => 4],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Bulilima', 'allocation' => 6],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Bulilima', 'allocation' => 6],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Bulilima', 'allocation' => 6],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Bulilima', 'allocation' => 6],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Bulilima', 'allocation' => 0],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Bulilima', 'allocation' => 1],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Bulilima', 'allocation' => 0],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Bulilima', 'allocation' => 0],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Bulilima', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Bulilima', 'allocation' => 0],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Bulilima', 'allocation' => 0],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Bubi', 'allocation' => 3],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Bubi', 'allocation' => 3],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Bubi', 'allocation' => 3],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Bubi', 'allocation' => 6],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Bubi', 'allocation' => 2],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Bubi', 'allocation' => 2],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Bubi', 'allocation' => 2],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Bubi', 'allocation' => 3],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Bubi', 'allocation' => 1],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Bubi', 'allocation' => 0],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Chipinge', 'allocation' => 4],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Chipinge', 'allocation' => 4],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Chipinge', 'allocation' => 2],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Chipinge', 'allocation' => 2],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Chipinge', 'allocation' => 2],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Chipinge', 'allocation' => 2],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Chipinge', 'allocation' => 2],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Chipinge', 'allocation' => 2],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Chipinge', 'allocation' => 0],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Chiredzi', 'allocation' => 23],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Chiredzi', 'allocation' => 23],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Chiredzi', 'allocation' => 20],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Chiredzi', 'allocation' => 30],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Chiredzi', 'allocation' => 22],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Chiredzi', 'allocation' => 1],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Chiredzi', 'allocation' => 1],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Chiredzi', 'allocation' => 1],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Chiredzi', 'allocation' => 2],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Chiredzi', 'allocation' => 3],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Chiredzi', 'allocation' => 6],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Chiredzi', 'allocation' => 5],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Chiredzi', 'allocation' => 5],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Chiredzi', 'allocation' => 8],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Chiredzi', 'allocation' => 8],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Chiredzi', 'allocation' => 37],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Chiredzi', 'allocation' => 36],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Chiredzi', 'allocation' => 47],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Chiredzi', 'allocation' => 49],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Chiredzi', 'allocation' => 52],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Chiredzi', 'allocation' => 10],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Chiredzi', 'allocation' => 10],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Chiredzi', 'allocation' => 13],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Chiredzi', 'allocation' => 4],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Chiredzi', 'allocation' => 16],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Chiredzi', 'allocation' => 9],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Chiredzi', 'allocation' => 7],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Chiredzi', 'allocation' => 11],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Chiredzi', 'allocation' => 10],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Chiredzi', 'allocation' => 12],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Gokwe North', 'allocation' => 4],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Gokwe North', 'allocation' => 4],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Gokwe North', 'allocation' => 4],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Gokwe North', 'allocation' => 4],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Gokwe North', 'allocation' => 4],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Gokwe North', 'allocation' => 4],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Gokwe North', 'allocation' => 4],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Gokwe North', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Gokwe North', 'allocation' => 1],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Gokwe South', 'allocation' => 4],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Gokwe South', 'allocation' => 4],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Gokwe South', 'allocation' => 4],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Gokwe South', 'allocation' => 4],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Gokwe South', 'allocation' => 4],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Gokwe South', 'allocation' => 4],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Gokwe South', 'allocation' => 4],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Gokwe South', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Gokwe South', 'allocation' => 1],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Hwange', 'allocation' => 11],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Hwange', 'allocation' => 0],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Hwange', 'allocation' => 9],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Hwange', 'allocation' => 10],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Hwange', 'allocation' => 10],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Hwange', 'allocation' => 1],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Hwange', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Hwange', 'allocation' => 2],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Hwange', 'allocation' => 1],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Hwange', 'allocation' => 1],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Hwange', 'allocation' => 2],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Hwange', 'allocation' => 0],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Hwange', 'allocation' => 3],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Hwange', 'allocation' => 2],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Hwange', 'allocation' => 2],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Hwange', 'allocation' => 6],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Hwange', 'allocation' => 0],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Hwange', 'allocation' => 10],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Hwange', 'allocation' => 5],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Hwange', 'allocation' => 5],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Hwange', 'allocation' => 3],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Hwange', 'allocation' => 0],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Hwange', 'allocation' => 3],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Hwange', 'allocation' => 6],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Hwange', 'allocation' => 3],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Hwange', 'allocation' => 4],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Hwange', 'allocation' => 0],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Hwange', 'allocation' => 3],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Hwange', 'allocation' => 3],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Hwange', 'allocation' => 5],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Hurungwe', 'allocation' => 21],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Hurungwe', 'allocation' => 21],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Hurungwe', 'allocation' => 21],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Hurungwe', 'allocation' => 21],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Hurungwe', 'allocation' => 21],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Hurungwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Mbire', 'allocation' => 26],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Mbire', 'allocation' => 24],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Mbire', 'allocation' => 24],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Mbire', 'allocation' => 21],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Mbire', 'allocation' => 20],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Mbire', 'allocation' => 4],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Mbire', 'allocation' => 5],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Mbire', 'allocation' => 5],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Mbire', 'allocation' => 4],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Mbire', 'allocation' => 3],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Mbire', 'allocation' => 9],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Mbire', 'allocation' => 9],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Mbire', 'allocation' => 9],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Mbire', 'allocation' => 9],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Mbire', 'allocation' => 5],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Mbire', 'allocation' => 47],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Mbire', 'allocation' => 47],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Mbire', 'allocation' => 46],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Mbire', 'allocation' => 47],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Mbire', 'allocation' => 47],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Mbire', 'allocation' => 11],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Mbire', 'allocation' => 11],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Mbire', 'allocation' => 11],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Mbire', 'allocation' => 11],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Mbire', 'allocation' => 6],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Mbire', 'allocation' => 7],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Mbire', 'allocation' => 7],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Mbire', 'allocation' => 7],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Mbire', 'allocation' => 6],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Mbire', 'allocation' => 6],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Mangwe', 'allocation' => 7],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Mangwe', 'allocation' => 5],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Mangwe', 'allocation' => 7],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Mangwe', 'allocation' => 6],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Mangwe', 'allocation' => 0],
            ['period' => '2019', 'species' => 'elephant', 'district' => 'Nyaminyami', 'allocation' => 12],
            ['period' => '2020', 'species' => 'elephant', 'district' => 'Nyaminyami', 'allocation' => 11],
            ['period' => '2021', 'species' => 'elephant', 'district' => 'Nyaminyami', 'allocation' => 11],
            ['period' => '2022', 'species' => 'elephant', 'district' => 'Nyaminyami', 'allocation' => 9],
            ['period' => '2023', 'species' => 'elephant', 'district' => 'Nyaminyami', 'allocation' => 10],
            ['period' => '2019', 'species' => 'lion', 'district' => 'Nyaminyami', 'allocation' => 0],
            ['period' => '2020', 'species' => 'lion', 'district' => 'Nyaminyami', 'allocation' => 0],
            ['period' => '2021', 'species' => 'lion', 'district' => 'Nyaminyami', 'allocation' => 0],
            ['period' => '2022', 'species' => 'lion', 'district' => 'Nyaminyami', 'allocation' => 0],
            ['period' => '2023', 'species' => 'lion', 'district' => 'Nyaminyami', 'allocation' => 0],
            ['period' => '2019', 'species' => 'leopard', 'district' => 'Nyaminyami', 'allocation' => 8],
            ['period' => '2020', 'species' => 'leopard', 'district' => 'Nyaminyami', 'allocation' => 0],
            ['period' => '2021', 'species' => 'leopard', 'district' => 'Nyaminyami', 'allocation' => 0],
            ['period' => '2022', 'species' => 'leopard', 'district' => 'Nyaminyami', 'allocation' => 10],
            ['period' => '2023', 'species' => 'leopard', 'district' => 'Nyaminyami', 'allocation' => 8],
            ['period' => '2019', 'species' => 'buffalo', 'district' => 'Nyaminyami', 'allocation' => 50],
            ['period' => '2020', 'species' => 'buffalo', 'district' => 'Nyaminyami', 'allocation' => 50],
            ['period' => '2021', 'species' => 'buffalo', 'district' => 'Nyaminyami', 'allocation' => 32],
            ['period' => '2022', 'species' => 'buffalo', 'district' => 'Nyaminyami', 'allocation' => 31],
            ['period' => '2023', 'species' => 'buffalo', 'district' => 'Nyaminyami', 'allocation' => 33],
            ['period' => '2019', 'species' => 'hippo', 'district' => 'Nyaminyami', 'allocation' => 47],
            ['period' => '2020', 'species' => 'hippo', 'district' => 'Nyaminyami', 'allocation' => 47],
            ['period' => '2021', 'species' => 'hippo', 'district' => 'Nyaminyami', 'allocation' => 52],
            ['period' => '2022', 'species' => 'hippo', 'district' => 'Nyaminyami', 'allocation' => 45],
            ['period' => '2023', 'species' => 'hippo', 'district' => 'Nyaminyami', 'allocation' => 45],
            ['period' => '2019', 'species' => 'crocodile', 'district' => 'Nyaminyami', 'allocation' => 25],
            ['period' => '2020', 'species' => 'crocodile', 'district' => 'Nyaminyami', 'allocation' => 25],
            ['period' => '2021', 'species' => 'crocodile', 'district' => 'Nyaminyami', 'allocation' => 22],
            ['period' => '2022', 'species' => 'crocodile', 'district' => 'Nyaminyami', 'allocation' => 23],
            ['period' => '2023', 'species' => 'crocodile', 'district' => 'Nyaminyami', 'allocation' => 24],

        ];

        foreach ($data as $item) {
            QuotaAllocation::create($item);
        }
    }
}
